import type { HealthReport } from "../types";

/** Encode analyze input + model into a shareable URL hash */
export function encodeShareURL(input: string, model: string): string {
  try {
    const payload = JSON.stringify({ input, model });
    const encoded = btoa(unescape(encodeURIComponent(payload)));
    const url = new URL(window.location.href);
    url.hash = `analyze=${encoded}`;
    return url.toString();
  } catch {
    return window.location.href;
  }
}

/** Decode a shareable URL hash into { input, model }, or null if not present */
export function decodeShareURL(): { input: string; model: string } | null {
  try {
    const hash = window.location.hash;
    if (!hash.startsWith("#analyze=")) return null;
    const encoded = hash.slice("#analyze=".length);
    const json = decodeURIComponent(escape(atob(encoded)));
    const parsed = JSON.parse(json);
    if (typeof parsed.input === "string" && typeof parsed.model === "string") {
      return { input: parsed.input, model: parsed.model };
    }
    return null;
  } catch {
    return null;
  }
}

/** Clear the share hash from the URL without triggering a reload */
export function clearShareHash(): void {
  if (window.location.hash.startsWith("#analyze=")) {
    history.replaceState(null, "", window.location.pathname + window.location.search);
  }
}

/** Download a PNG summary card for the given HealthReport */
export function exportReportPNG(report: HealthReport): void {
  const canvas = document.createElement("canvas");
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  const W = 640;
  const H = 360;
  canvas.width = W * dpr;
  canvas.height = H * dpr;
  canvas.style.width = `${W}px`;
  canvas.style.height = `${H}px`;

  const ctx = canvas.getContext("2d");
  if (!ctx) return;
  ctx.scale(dpr, dpr);

  // Background
  ctx.fillStyle = "#0f1117";
  ctx.fillRect(0, 0, W, H);

  // Border
  ctx.strokeStyle = "#1e2230";
  ctx.lineWidth = 1;
  ctx.strokeRect(0.5, 0.5, W - 1, H - 1);

  // Header band
  ctx.fillStyle = "#13161f";
  ctx.fillRect(0, 0, W, 56);
  ctx.fillStyle = "#1e2230";
  ctx.fillRect(0, 55, W, 1);

  // Logo text
  ctx.font = "bold 16px system-ui, sans-serif";
  ctx.fillStyle = "#6d7ad8";
  ctx.fillText("ContextLens", 24, 35);

  // Score color
  const scoreColor =
    report.score >= 85 ? "#22c55e" :
    report.score >= 70 ? "#84cc16" :
    report.score >= 50 ? "#eab308" :
    report.score >= 30 ? "#f97316" : "#ef4444";

  // Big score
  ctx.font = "bold 64px monospace";
  ctx.fillStyle = scoreColor;
  ctx.fillText(String(report.score), 24, 140);

  ctx.font = "13px system-ui, sans-serif";
  ctx.fillStyle = "#94a3b8";
  ctx.fillText(`/ 100  ·  ${report.scoreLabel.toUpperCase()}`, 24, 162);

  // Token stats
  ctx.font = "12px monospace";
  ctx.fillStyle = "#64748b";
  ctx.fillText(
    `${report.context.totalTokens.toLocaleString()} tokens  ·  ${report.context.model}  ·  ${((report.context.totalTokens / report.context.modelMaxTokens) * 100).toFixed(1)}% of window`,
    24,
    190
  );

  // Sub-scores
  const subs = [
    ["Token Efficiency", report.breakdown.tokenEfficiency],
    ["Recency Dist.", report.breakdown.recencyDistribution],
    ["Identity Survival", report.breakdown.identitySurvival],
    ["Poison Risk", report.breakdown.poisonRisk],
    ["Compressibility", report.breakdown.compressionOpportunity],
  ] as [string, number][];

  const barW = 280;
  const barX = 24;
  const subY0 = 218;

  subs.forEach(([label, val], i) => {
    const y = subY0 + i * 22;
    ctx.font = "11px system-ui, sans-serif";
    ctx.fillStyle = "#64748b";
    ctx.fillText(label, barX, y);

    const numStr = String(val);
    ctx.fillStyle = "#94a3b8";
    ctx.fillText(numStr, barX + 140, y);

    // Background bar
    ctx.fillStyle = "#1e2230";
    ctx.fillRect(barX + 160, y - 10, barW - 160, 9);
    // Fill bar
    const barColor = val > 70 ? "#22c55e" : val > 40 ? "#eab308" : "#ef4444";
    ctx.fillStyle = barColor;
    ctx.fillRect(barX + 160, y - 10, ((barW - 160) * val) / 100, 9);
  });

  // Risks count
  ctx.font = "bold 12px system-ui, sans-serif";
  ctx.fillStyle = report.risks.length > 0 ? "#f87171" : "#22c55e";
  ctx.fillText(
    report.risks.length > 0
      ? `${report.risks.length} risk${report.risks.length > 1 ? "s" : ""} detected`
      : "No risks detected",
    W / 2 + 20,
    220
  );

  // Top risk
  if (report.risks[0]) {
    ctx.font = "11px system-ui, sans-serif";
    ctx.fillStyle = "#94a3b8";
    const riskText = `↳ ${report.risks[0].title}`;
    ctx.fillText(riskText.slice(0, 42), W / 2 + 20, 240);
  }

  // Footer
  ctx.fillStyle = "#1e2230";
  ctx.fillRect(0, H - 32, W, 1);
  ctx.font = "11px system-ui, sans-serif";
  ctx.fillStyle = "#334155";
  ctx.fillText("Generated by ContextLens · MIT License", 24, H - 12);

  // Download
  canvas.toBlob((blob) => {
    if (!blob) return;
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `contextlens-report-${report.score}.png`;
    a.click();
    URL.revokeObjectURL(a.href);
  }, "image/png");
}
